**Numpy_Intro**

* It is fundamental package for scientific computing with python. 
* It is also known as numerical python.
* It is powerful N-Dimensional array object.
* It's main object homogenous multi dimensional array.
* In Numpy, dimensions are called as axes.

**Various Functions of Numpy**

* array(object)
* zeros(size)
* ones(size)
* arange(size)
* full(size, fill_value)


**Creating Array**

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [16]:
a = np.array((1,2,3))

In [17]:
a


array([1, 2, 3])

In [18]:
type(a)

numpy.ndarray

In [19]:
np.shape(a)

(3,)

In [25]:
langs = np.array(['c', 'c##', 'python', 'r'])

In [26]:
langs

array(['c', 'c##', 'python', 'r'], dtype='<U6')

In [27]:
a = np.array([1,2, 'abc'])

In [28]:
a


array(['1', '2', 'abc'], dtype='<U11')

In [29]:
np.shape(a)

(3,)

In [30]:
type(a)

numpy.ndarray

**Difference between array and list** 

In [39]:
a = np.array([1,2,3,4])
a * 2 # Multiplication

array([2, 4, 6, 8])

In [37]:
a ** 3

array([ 1,  8, 27, 64], dtype=int32)

In [45]:
l = [1,2,3,4]
l * 4          #Replication

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [44]:
l + l

[1, 2, 3, 4, 1, 2, 3, 4]

**Other ways to create Arrays**

In [48]:
a = np.arange(10)

In [49]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a = np.arange(24).reshape(4,6)

In [127]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
a = np.arange(0,10)

In [52]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a = np.ones((3,3), dtype = int)

In [79]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [80]:
a = np.zeros(3)

In [92]:
a, a.dtype

(array([1, 1, 1]), dtype('int32'))

In [93]:
a = np.ones(3, dtype = np.int32)

In [94]:
a

array([1, 1, 1])

In [70]:
a = np.full(3,3)
a

array([3, 3, 3])

In [75]:
a = np.full((3,3), 2, dtype = None)
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [76]:
a = np.full((2,2), (1,2))

In [77]:
a

array([[1, 2],
       [1, 2]])

**Random Numbers Generation**

In [96]:
a = np.random.rand(10)

In [97]:
a

array([0.81172758, 0.52032376, 0.94941573, 0.41791359, 0.85781323,
       0.14753238, 0.81876734, 0.23565003, 0.29162804, 0.80123345])

In [98]:
for a in a:
    print(a)

0.8117275809273867
0.5203237602510616
0.9494157305699791
0.4179135892863556
0.8578132335573728
0.1475323767815332
0.8187673385706972
0.23565003125441275
0.29162804207082493
0.8012334505866064


In [154]:
import numpy as np
import random

In [158]:
a = np.random.randint(1,26,(5,5))
avg = a.mean()
# boolean indexing
a[a> a.mean()]

array([23, 22, 21, 22, 22, 23, 20, 17, 18, 15, 14, 24])

In [159]:
a = np.random.randint(1,26,(5,5))


In [160]:
a

array([[12,  9, 15, 11, 18],
       [14, 13, 21, 13,  5],
       [ 7, 20, 19, 10, 14],
       [11,  9, 17, 13,  1],
       [16, 16, 16,  4, 19]])

In [40]:
a = np.random.randint(1,26,(5,5))
a.mean()
a[a> a.mean()]

array([24, 23, 15, 19, 22, 18, 22, 15, 18, 20, 23, 25, 18, 19, 15])

In [162]:
a > a.mean()

array([[False, False,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True, False,  True],
       [False, False,  True,  True, False],
       [ True,  True,  True, False,  True]])

In [163]:
a[a> a.mean()]

array([15, 18, 14, 13, 21, 13, 20, 19, 14, 17, 13, 16, 16, 16, 19])

In [164]:
a = np.arange(1,26).reshape(5,5)


In [165]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [173]:
a= np.zeros((3,3), dtype= int)

In [171]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [174]:
a = np.ones((5,5), dtype= int)

In [175]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [176]:
a.mean()

1.0

In [177]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [178]:
a > 0.5

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [179]:
a[a>0.5]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

**linsapce()**

* **Retuns a arrey with evenly spaced numbers over a specific interval**
* **linspce(start,end,retstep,dtype)**


In [9]:
a = np.linspace(1,10,5)

In [10]:
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
a = np.linspace(1,10,5, retstep = True, dtype= int)

In [15]:
a

(array([ 1,  3,  5,  7, 10]), 2.25)

**Class ndarray**

In [18]:
a = np.random.randint(1,10,(5,2))

In [19]:
a

array([[1, 9],
       [5, 8],
       [3, 8],
       [6, 6],
       [7, 7]])

In [22]:
print(a.shape, a.size,a.ndim, a.dtype)

(5, 2) 10 2 int32


**Indexing & Slicing** 

In [25]:
a = np.arange(1,10)

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[0:2]

array([1, 2])

In [31]:
a[1:15]  # end value can be of any numbers

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a[:]  # returns all numbers in an array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[5:]

array([6, 7, 8, 9])

In [35]:
a[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
a[-1]

9

In [37]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [43]:
a  = np.random.randint(1,26,(5,5))

In [44]:
a

array([[18, 13,  1, 10, 15],
       [ 5,  8, 25,  5, 10],
       [20, 15, 17,  1, 18],
       [19, 17,  5, 14, 20],
       [ 4, 25, 18, 11, 17]])

In [47]:
a[1:4]

array([[ 5,  8, 25,  5, 10],
       [20, 15, 17,  1, 18],
       [19, 17,  5, 14, 20]])

In [48]:
a[1:4, :]

array([[ 5,  8, 25,  5, 10],
       [20, 15, 17,  1, 18],
       [19, 17,  5, 14, 20]])

In [49]:
a[1:4, 1:4]

array([[ 8, 25,  5],
       [15, 17,  1],
       [17,  5, 14]])

In [54]:
a = np.random.randint(1,26,(5,5))


In [55]:
a

array([[ 6, 15,  6, 12, 23],
       [ 3, 14, 14, 20, 22],
       [20, 12, 11,  7, 25],
       [ 1, 22, 25, 20, 15],
       [ 9, 13,  7,  9,  7]])

In [56]:
a[3:, -2:]

array([[20, 15],
       [ 9,  7]])

In [57]:
a[::-1]

array([[ 9, 13,  7,  9,  7],
       [ 1, 22, 25, 20, 15],
       [20, 12, 11,  7, 25],
       [ 3, 14, 14, 20, 22],
       [ 6, 15,  6, 12, 23]])

In [58]:
a[::-1, ::-1]

array([[ 7,  9,  7, 13,  9],
       [15, 20, 25, 22,  1],
       [25,  7, 11, 12, 20],
       [22, 20, 14, 14,  3],
       [23, 12,  6, 15,  6]])

In [59]:
a[::2]

array([[ 6, 15,  6, 12, 23],
       [20, 12, 11,  7, 25],
       [ 9, 13,  7,  9,  7]])

In [60]:
a[::3]

array([[ 6, 15,  6, 12, 23],
       [ 1, 22, 25, 20, 15]])

In [62]:
a[::3, 2:4 ]

array([[ 6, 12],
       [25, 20]])

**Index by Array**

In [24]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[[0,2]], a[6], a[[1,5,7]]

(array([1, 3]), 7, array([2, 6, 8]))

In [33]:
a = np.random.randint(1,37,(6,6))
a

array([[18, 10,  8,  5,  3,  6],
       [ 7,  6, 18, 19, 30,  3],
       [19,  5, 20, 33,  4,  6],
       [13, 11,  1,  5, 35, 23],
       [13, 13, 23,  9,  8, 18],
       [29, 11, 20, 27, 29, 16]])

In [36]:
a[[0,3,5], [0,1,2]]

array([18, 11, 20])

In [37]:
a[[1,2,4], [2,3,5]]

array([18, 33, 18])

In [47]:
a[[0,3,5]]

array([[18, 10,  8,  5,  3,  6],
       [13, 11,  1,  5, 35, 23],
       [29, 11, 20, 27, 29, 16]])

In [48]:
a[[0,3,5], [2,3,5]]

array([ 8,  5, 16])

In [51]:
a[[0,2]]

array([[18, 10,  8,  5,  3,  6],
       [19,  5, 20, 33,  4,  6]])

**Iterate**

In [70]:
a = np.arange(10)
for n in a :
    print(n, end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [71]:
a = np.random.randint(1,26,(5,5))

In [72]:
a

array([[24,  8,  2, 21, 25],
       [18,  3, 23, 11, 15],
       [18,  2, 17, 22,  4],
       [13, 20,  3,  8, 15],
       [17, 13,  6, 15,  8]])

In [74]:
for row in a:
    for col in row:
        if col % 2 == 0:
            print(col, end = ' ')

24 8 2 18 18 2 22 4 20 8 6 8 

In [22]:
## To get odd numbers from an array
import numpy as np
a = np.arange(1,26).reshape(5,5)
odd = a[a%2 == 1]
len(odd)

13

**Boolean Indexing**

In [54]:
a = np.random.randint(1,26,(5,5))

In [55]:
a>10

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True, False,  True,  True,  True],
       [False,  True, False,  True, False],
       [False,  True,  True,  True, False]])

In [56]:
a % 2 == 1   # odd number 

array([[False,  True, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True, False,  True]])

In [57]:
evens = a[a%2 == 0]   # to print all the elements

In [58]:
evens

array([20, 22, 24,  4,  8, 10, 12])

**To create 5x5 array with random numbers and display elements greater than avg of an array**`

In [68]:
a = np.random.randint(1,26,(5,5))
avg = a.mean()
a[a> avg]           #boolean Indexing

array([20, 21, 23, 24, 18, 21, 14, 13, 14, 17, 17, 25])

**Array Operations**

In [71]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [83]:
b = a + 5.5
np.array(b, dtype = int)

array([ 6,  7,  8,  9, 10])

In [95]:
 b -= 5.5
 np.array(b, dtype = int)   

array([1, 2, 3, 4, 5])

In [96]:
a == b

array([ True,  True,  True,  True,  True])

In [99]:
print(np.add(a,b))
print(a+b)

[ 2.  4.  6.  8. 10.]
[ 2.  4.  6.  8. 10.]


In [101]:
a1 = np.arange(1,6)
a2 = np.arange(1,6)
a1 == a2

array([ True,  True,  True,  True,  True])

**ALL Vs. ANY**

In [102]:
a1.all()        # if all elements are true all ret. true 

True

In [103]:
a2.any()

True

In [111]:
a = np.arange(1,6)
ba = a % 2 == 0

In [112]:
ba.all()

False

In [113]:
ba.any()

True

In [114]:
a1 > 4.4

array([False, False, False, False,  True])

In [116]:
a2> 2.25

array([False, False,  True,  True,  True])

**Methods of ndarray**

In [118]:
a = np.random.randint(1,100,(6,6))
a.sum()

2196

In [119]:
s = np.sum(a)

In [120]:
s

2196

In [130]:
a = np.arange(40,55, 3)

In [131]:
a

array([40, 43, 46, 49, 52])

In [137]:
 (a>50).all()


False

In [138]:
a = np.random.randint(1,100,(6,6))
a

array([[49, 97, 41, 86,  8, 61],
       [75, 30, 69, 75, 48, 34],
       [ 6,  4, 20,  6, 48, 36],
       [48,  1, 68, 51, 24, 70],
       [25, 84, 77, 34, 40, 68],
       [39, 91, 56, 19,  8, 33]])

In [155]:
for n in a:
    print((n%2 == 0).sum())
    
        

2
3
6
4
4
2


**To print no of odd numbers in each row**

In [153]:
for idx, row in enumerate(a):
    print(idx, (row%2==1).sum())

0 4
1 3
2 0
3 2
4 2
5 4


In [159]:
a = np.array([True, False, True])
print(a.sum())   # true = 1 , False = 0

2


In [171]:
# how many students passed the exam
marks = np.random.randint(1,100,(6,6))
(marks > 50).sum()

17

In [177]:
marks.sum() , 
marks.sum(axis = 0), marks.sum(axis = 1)    # axis = 0 column wise sum , axis= 1 row wise sum 

(array([161, 342, 332, 221, 339, 179]), array([234, 297, 160, 346, 338, 199]))

In [182]:
marks , marks.cumsum(axis =  0), marks.cumsum(axis = 1)

(array([[11,  4, 71, 55, 57, 36],
        [72, 73, 67,  5, 48, 32],
        [ 3, 59, 14,  6, 55, 23],
        [42, 90, 91, 98, 18,  7],
        [24, 59, 72, 54, 86, 43],
        [ 9, 57, 17,  3, 75, 38]]),
 array([[ 11,   4,  71,  55,  57,  36],
        [ 83,  77, 138,  60, 105,  68],
        [ 86, 136, 152,  66, 160,  91],
        [128, 226, 243, 164, 178,  98],
        [152, 285, 315, 218, 264, 141],
        [161, 342, 332, 221, 339, 179]], dtype=int32),
 array([[ 11,  15,  86, 141, 198, 234],
        [ 72, 145, 212, 217, 265, 297],
        [  3,  62,  76,  82, 137, 160],
        [ 42, 132, 223, 321, 339, 346],
        [ 24,  83, 155, 209, 295, 338],
        [  9,  66,  83,  86, 161, 199]], dtype=int32))

In [187]:
(marks>50).sum(axis = 0) , (marks> 50).sum(axis = 1)

(array([1, 5, 4, 3, 4, 0]), array([3, 3, 2, 3, 4, 2]))

In [188]:
#sum of alternate row
marks[::2].sum()

732

In [189]:
marks[1:2 , 2:4].sum()  #slicing

72

In [192]:
marks[[0,3,5]],marks[[0,3,5]].sum()

(array([[11,  4, 71, 55, 57, 36],
        [42, 90, 91, 98, 18,  7],
        [ 9, 57, 17,  3, 75, 38]]),
 779)

In [193]:
marks

array([[11,  4, 71, 55, 57, 36],
       [72, 73, 67,  5, 48, 32],
       [ 3, 59, 14,  6, 55, 23],
       [42, 90, 91, 98, 18,  7],
       [24, 59, 72, 54, 86, 43],
       [ 9, 57, 17,  3, 75, 38]])

In [202]:
cum = marks.cumsum(axis = 0)
cum

array([[ 11,   4,  71,  55,  57,  36],
       [ 83,  77, 138,  60, 105,  68],
       [ 86, 136, 152,  66, 160,  91],
       [128, 226, 243, 164, 178,  98],
       [152, 285, 315, 218, 264, 141],
       [161, 342, 332, 221, 339, 179]], dtype=int32)

In [203]:
cum.argmin(), cum.argmax()

(1, 31)

In [207]:
marks

array([[11,  4, 71, 55, 57, 36],
       [72, 73, 67,  5, 48, 32],
       [ 3, 59, 14,  6, 55, 23],
       [42, 90, 91, 98, 18,  7],
       [24, 59, 72, 54, 86, 43],
       [ 9, 57, 17,  3, 75, 38]])

**Sorting**

In [212]:
a = np.array([5,6,9,1])
sorted(a)

[1, 5, 6, 9]

In [214]:
a.sort()

In [215]:
a

array([1, 5, 6, 9])

In [216]:
s = np.sort(a)

In [217]:
s

array([1, 5, 6, 9])

**2-D Array**

In [227]:
a = np.random.randint(1,100,(3,3))

In [228]:
a

array([[66, 38, 40],
       [73,  2, 71],
       [83, 72,  7]])

In [229]:
a.sort()

In [230]:
a   # row wise sorting

array([[38, 40, 66],
       [ 2, 71, 73],
       [ 7, 72, 83]])

In [235]:
a.sort(axis = -1)

In [236]:
a  # column wise sorting

array([[ 2, 40, 66],
       [ 7, 71, 73],
       [38, 72, 83]])

In [240]:
fa = np.sort(a, axis = None)  # sorting after flattening it

In [241]:
fa

array([ 2,  7, 38, 40, 66, 71, 72, 73, 83])

In [249]:
s = np.array([fa]).reshape(3,3)

In [250]:
s

array([[ 2,  7, 38],
       [40, 66, 71],
       [72, 73, 83]])

**Sorting Whole 2-D array**

In [261]:
a = np.random.randint(1,500,(10,10))
flat_a = np.sort(a, axis = None)
sort = np.array([flat_a]).reshape(10,10)
sort

array([[  1,   5,  11,  11,  12,  17,  18,  19,  24,  37],
       [ 54,  56,  56,  58,  64,  69,  78,  79,  87,  90],
       [ 92, 104, 115, 116, 116, 120, 122, 136, 143, 154],
       [167, 171, 171, 179, 179, 182, 186, 194, 202, 202],
       [212, 215, 217, 228, 232, 240, 251, 254, 254, 255],
       [260, 274, 287, 290, 291, 294, 294, 296, 302, 302],
       [304, 311, 321, 321, 324, 342, 343, 350, 355, 357],
       [359, 368, 370, 372, 372, 388, 390, 390, 401, 404],
       [411, 426, 429, 437, 440, 441, 444, 448, 456, 460],
       [464, 466, 470, 472, 478, 479, 485, 491, 494, 495]])